exercise= "python programming".title()
print(exercise)
exercise=" hello world ".strip()
print(exercise)
exercise="banana".count("a")
print(exercise)
exercise="hello world".split()
print(exercise)
exercise="-".join(["2024","01","15"])
print(exercise)